name: Build asterix_b2b2v2 firmware

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install a compiler
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        with:
          release: '13.2.Rel1'
      
      - name: Checkout submodules
        run: GIT_LFS_SKIP_SMUDGE=1 git submodule update --init --recursive --progress
      
      - name: Configure cmake
        run: cmake -B build -DPICO_SDK_FETCH_FROM_GIT=on -DPICOTOOL_FORCE_FETCH_FROM_GIT=1
    
      - name: Build
        run: make -C build
    
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: asterix_b2b2v2
          path: |
            build/asterix_b2b2v2.*